
user  nginx;
worker_processes  auto;

error_log  logs/error.log  warn;
pid        logs/nginx.pid;


events {
    worker_connections  1024;
}

include /opt/verynginx/nginx_conf/in_external.conf;

http {
    include       mime.types;
    default_type  application/octet-stream;

    log_format v2 '$remote_addr - $remote_user [$time_local] "$request" '
                  '$status $body_bytes_sent "$http_referer" '
                  '"$http_user_agent" "$http_x_forwarded_for" '
                  'rt=$request_time uct=$upstream_connect_time uht=$upstream_header_time urt=$upstream_response_time';

    access_log  logs/access.log  v2;
    sendfile        on;
    #tcp_nopush     on;

    #keepalive_timeout  0;
    keepalive_timeout  65;
	client_body_buffer_size 128k;

    #gzip  on;
	
	#this line shoud be include in every http block
    include /opt/verynginx/nginx_conf/in_http_block.conf;

    server {
        listen       80;

        #this line should be include in every server block
        include /opt/verynginx/nginx_conf/in_server_block.conf;

        # Default location: redirect root to VeryNginx dashboard
        location = / {
            return 302 /verynginx/index.html;
        }
    }

}
