-- -*- coding: utf-8 -*-
-- @Date    : 2026-07-15
-- @Author  : VeryNginx v2
-- @Disc    : version info — reads VERSION file generated by install, falls back to git

local _M = {}

local function prefix()
    return debug.getinfo(1, "S").source:match("^@(.+)/core/")
        or "/opt/verynginx"
end

function _M.get()
    local f = io.open(prefix() .. "/VERSION", "r")
    if f then
        local content = f:read("*a")
        f:close()
        if content then
            content = content:match("^%s*(.-)%s*$")
            if content ~= "" then
                return content
            end
        end
    end
    return "dev"
end

function _M.commit()
    local f = io.open(prefix() .. "/COMMIT", "r")
    if f then
        local c = f:read("*a")
        f:close()
        if c then
            c = c:match("^%s*(.-)%s*$")
            if c ~= "" then
                return c
            end
        end
    end
    return "unknown"
end

return _M
