# VeryNginx v2 - external configuration
# This file should be included outside any block

# Dynamic upstream for balancer_by_lua
upstream vn_dynamic_upstream {
    server 0.0.0.1;
    balancer_by_lua_block {
        require("plugin.proxy_pass.balancer").run()
    }
    keepalive 128;
}

# Lua package paths
lua_package_path '/opt/verynginx/verynginx/?.lua;;';
lua_package_cpath '/opt/verynginx/verynginx/?.so;;';
lua_code_cache on;